# Generated by Django 6.0.6 on 2026-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='live_video',
            field=models.FileField(blank=True, null=True, upload_to='channel_videos/'),
        ),
        migrations.AddField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
