# Generated by Django 6.0.6 on 2026-06-15 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_channel_live_video_channel_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_banners', to='home.show'),
        ),
    ]
